name 'php-fpm'
version '0.0.1'
source 'https://github.com/booo/puppet-php-fpm.git'
author 'Philipp Borgers'
license 'MIT'
summary 'Lightweight for php-fpm and only php-fpm'
project_page 'https://github.com/booo/puppet-php-fpm'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
